---
title: "final"
format: html
editor: visual
---

\[Github Repo\]()

## set up

```{r}
#load packages and reading data
library(tidyverse)
library(janitor)
library(lubridate)

#reading csv data file 
sst <- read.csv("Data/SST_sb_channel.csv")

```

## Problem 1. Research Writing

### a. Transparent statistical methods

In part 1, they used a correlation test. They most likely used Pearson correlation test since both variables are continuous and they are assessing the linear relationship between distance from headwater and annual total nitrogen load. But there is not enough information to confidently determine if they used Pearson or Spearman correlation test.

In part 2, they used one-way ANOVA. They compared the average in nitrogen load (mean) with 5 variables. ANOVA test is used to test for statistical significant differences between the means of 2 or more groups.

### b. More information needed

-   Summary statistics

    adding summary statistics like the mean, standard deviation and sample size can helps us understand the magnitud and variability of the nitrogen loads for each source. For example the mean would gives us information about how much each source contributes.

-   Performing Tukey HSD

    This test would help us identify which nitrogen sources is significantly different when we compare them since ANOVA tells us there is significant difference but not from which sources, this test would helps us identify that.

### c. Suggestion for rewriting

Part 1:

We found a statistically significant positive relationship between distance from headwater and total nitrogen load, suggesting that nitrogen accumulates downstream, possibly due to agricultural and urban inputs.\
(Pearson correlation test: r = \[correlation coefficient\], p = 0.03, α = 0.05)

Part 2:

Average nitrogen load differed significantly among the five nitrogen sources, indicating that some sources contribute more nitrogen than others.(One-way ANOVA: F = \[F statistic\], df = \[degrees of freedom\], p = 0.02, α = 0.05).

## Problem 2. Data visualization
